name: 'Build old iomega/spec2vec files'

on: [push, pull_request]

jobs:

  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: iomega-spec2vec
          environment-file: environment.yml
          condarc-file: condarc.yml
          auto-activate-base: false
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Check style against standards using prospector
        shell: bash -l {0}
        run: prospector
      - name: Build
        shell: bash -l {0}
        run: |
          python setup.py build
      - name: Test
        shell: bash -l {0}
        run: |
          python setup.py test
